app.js
controller/reservation.controller.js
models/reservation.js
repository/reservation.repositroy.js
routes/index.routes.js
routes/reservation.routes.js
service/reservation.service.js

구현중 내용
1. reservation post 3 Layered 로 구현중
2. models 에서 reservation 컬럼 정리 (담당자와 이야기하면서 바뀔 수 있음)
fix 내용
1. routes에 있는 middlewear 에서 import 문제가 나와 middlewear 삭제하니 서버 정상작동됨

fix: #5 기업 회원 면접 예약 구현중 22-11-12 16:10(최예닮)

---

models/index.js

구현 내용
1. models 에 index 파일에서 몽구스 dbName 추가

fix: 몽구스dbName 추가 22-11-12 17:24(최예닮)

---

repository/reservation.repository.js

fix: #2 충돌 오류수정 추가 22-11-12 21:46 (장민영)

---

.gitignore 2
.prettierrc.js
app.js
controller/members.controller.js
middleware/auth_middleware.js
models/expirationMember.js
models/members.js
models/refresh.js
models/reservation.js
package-lock.json
package.json
repository/members.repository.js
repository/reservation.repositroy.js
routes/members.routes.js
schedule.js
service/members.service.js
service/reservation.service.js

feat: 1달 동안 로그인 하지 않은 유저의 계정 정지 기능 2차 구현 22-11-14 09:51 (김민섭)
1. 1차 구현 후 파일 정리

Minseobfeat: 1달 동안 로그인 하지 않은 유저의 계정 정지 기능 2차 구현 22-11-14 09:51 (김민섭)

---

.gitignore 2
controller/reservation.controller.js
repository/reservation.repository.js
routes/reservation.routes.js
service/reservation.service.js

구현 내용
1. reservation 3 layred 에서 body 값 interviewTopic, interviewTime 추가
2. 프리티어로 충돌나는 부분 해결

fix: #5 면접 예약 구현중body 값 변경 22-11-14 10:17(최예닮)

---

models/members.js
models/refresh.js
models/reservation.js
models/users.js
schedule.js

chore: createdAt, updatedAt ISO --> 대한민국 표준시로 변경 22-11-14 10:37 (김민섭)

chore: createdAt, updatedAt ISO --> 대한민국 표준시로 변경 22-11-14 10:37 (김민섭)

---

controller/members.controller.js
models/members.js
repository/members.repository.js
repository/reservation.repository.js
schedule.js
service/members.service.js

1. 회원 수정, 탈퇴 try-catch 작성으로 에러 핸들링 구현
2. expirationMembers DB에 있던 정보들 회원 DB로 이동

chore: #4 회원 수정, 탈퇴 try-catch 작성 22-11-14 21:28 (김민섭)

---

controller/members.controller.js
jwt/jwt-utils.js
middleware/auth_middleware.js

1. 로그인 기능 2차 구현 (jwt expired 오류 메세지 수정)

chore: #3 로그인 기능 2차 구현 22-11-15 20:45 (김민섭)

---

controller/company.controller.js
middleware/company_auth.js
models/company.js
repository/company.repository.js
routes/company.routes.js
routes/index.routes.js
service/company.service.js

지속적인 문제로 pull 받을때 --rebase붙이는 방향으로 해결중

chore: #2 깃 문제 해결중 22-11-15 21:40(장민영)

---

controller/members.controller.js
repository/members.repository.js
service/members.service.js

fix: 회원가입 repo 버그 해결 22-11-16 01:01 (김민섭)

fix: 회원가입 repo 버그 해결 22-11-16 01:01 (김민섭)

---

routes/members.routes.js

fix: 개인회원 로그인 메소드 get -> post 로 변경 22-11-16 01:09 (김민섭)

fix: 개인회원 로그인 메소드 get -> post 로 변경 22-11-16 01:09 (김민섭)

---

controller/company.controller.js
controller/members.controller.js
models/company.js
models/members.js
package-lock.json
package.json
repository/company.repository.js
repository/members.repository.js
routes/members.routes.js
service/company.service.js
service/members.service.js

fix:#2 깃충돌 오류 수정  22-11-17 17:26(장민영)

---

controller/members.controller.js
routes/members.routes.js

fix: #4 개인정보 조회 토큰 만료시 뜨는 에러 수정 22-11-17 22:21 (김민섭)

fix: #4 개인정보 조회 토큰 만료시 뜨는 에러 수정 22-11-17 22:21 (김민섭)

---

routes/members.routes.js

fix: members/refersh 메소드 GET -> POST로 변경 22-11-17 22:29 (김민섭)

fix: members/refersh 메소드 GET -> POST로 변경 22-11-17 22:29 (김민섭)

---

jwt/refreshToken.js

chore: refreshToken 프론트와 통신 작업 중 22-11-17 23:22 (김민섭)

chore: refreshToken 프론트와 통신 작업 중 22-11-17 23:22 (김민섭)

---

controller/members.controller.js
jwt/jwt-utils.js
jwt/refreshToken.js

chore: refreshToken 프론트와 통신 작업 중 22-11-18 00:17 (김민섭)

chore: refreshToken 프론트와 통신 작업 중 22-11-18 00:17 (김민섭)

---

jwt/jwt-utils.js
jwt/refreshToken.js
models/refresh.js

chore: req.headers 콘솔 확인 22-11-18 00:42 (김민섭)

chore: req.headers 콘솔 확인 22-11-18 00:42 (김민섭)

---

jwt/refreshToken.js

chore: req.headers 콘솔 로그 추가 22-11-18 00:45 (김민섭)

chore: req.headers 콘솔 로그 추가 22-11-18 00:45 (김민섭)

---

jwt/refreshToken.js

chore: 상태메세지 추가 22-11-18 00:58 (김민섭)

chore: 상태메세지 추가 22-11-18 00:58 (김민섭)

---

controller/members.controller.js
jwt/jwt-utils.js
jwt/refreshToken.js

fix: #3 잘못된 refreshToken 값이 들어왔을 때 에러 메세지 띄우기 22-11-18 14:23 (김민섭)

fix: #3 잘못된 refreshToken 값이 들어왔을 때 에러 메세지 띄우기 22-11-18 14:23 (김민섭)

---

controller/members.controller.js
package-lock.json
package.json
routes/members.routes.js
service/members.service.js

feat: #2 이메일인증 구현중(인증코드 구현예정) 22-11-18 15:01(장민영)

---

app.js
controller/members.controller.js
jwt/refreshToken.js
routes/members.routes.js
schedule/schedule.js
service/members.service.js

fix: #3 로그인 시  이메일이 일치하지 않을 때 발생하는 오류 메세지 추가
"err.message" => "이메일 또는 비밀번호가 일치하지 않습니다"

fix: #3 로그인 시  이메일이 일치하지 않을 때 발생하는 오류 메세지 수정 22-11-21 15:47 (김민섭)

---

app.js

fix: app.js cannot find expiration 오류 수정 22-11-21 16:59 (김민섭)

fix: app.js cannot find expiration 오류 수정 22-11-21 16:59 (김민섭)

---

app.js
controller/reservation.controller.js
models/company.js
models/reservation.js
repository/reservation.repository.js
routes/index.routes.js
routes/reservation.routes.js
server.js
service/reservation.service.js
socket.js

구현 내용
1. webRTC 기본뼈대 작성
2. webRTC 서버연결을 위해 server 파일 추가
3. put) reservation 에서 url을  난수로 랜덤 생성할 수 있게 구현

feat: #12 webRTC 기본뼈대 파일 추가, webRTC를 위한 server 파일 추가 22-11-21 20:16(최예닮)

---

controller/company.controller.js
controller/members.controller.js
repository/company.repository.js
repository/members.repository.js
service/company.service.js
service/members.service.js

merge:#2 merge origin dev 22-11-21 20:39(장민영)

---

config/email.js
controller/members.controller.js
package-lock.json
package.json
routes/members.routes.js
service/members.service.js

feat: #2 회원가입시 이메일 인증 기능 2차 구현 완료 22-11-22 15:33(장민영)

---

controller/reservation.controller.js
package-lock.json
socket.js

feat: #12 webRTC 기본뼈대 추가 2차 22-11-22 15:45(최예닮)

feat: #12 webRTC 기본뼈대 추가 2차 22-11-22 15:45(최예닮)

---

app.js
controller/members.controller.js
jwt/jwt-utils.js
repository/members.repository.js
schedule/schedule.js
service/members.service.js
socket.js

feat, fix: membersService 리펙토링 및 webRTC 기본적인 코드 작성 22-11-22 15:43 (김민섭)
fix: 깃 충돌 수정 22-11-22 15:56 (김민섭)

feat, fix: membersService 리펙토링 및 webRTC 기본적인 코드 작성 22-11-22 15:43 (김민섭)

---

jwt/jwt-utils.js
jwt/refreshToken.js

fix: accessToken 만료 시 재발급 요청이 들어왔을 때 res 값에 refreshToken 값은 빼고 보내주는 것으로 수정

fix: #3 accessToken 만료 시 재발급 요청이 들어왔을 때 res 값에 refreshToken 값은 빼고 보내주는 것으로 수정 22-11-22 16:05 (김민섭)

---

routes/members.routes.js

fix: members/me router 경로 변경 22-11-22 16:21 (김민섭)

fix: members/me router 경로 변경 22-11-22 16:21 (김민섭)

---

controller/members.controller.js
jwt/refreshToken.js

fix: #3 accessToken 재발급 시 토큰값이 잘못 들어가는 오류 수정 22-11-22 16:56 (김민섭)

fix: #3 accessToken 재발급 시 토큰값이 잘못 들어가는 오류 수정 22-11-22 16:56 (김민섭)

---

socket.js

fix: #12 cors 설정 수정 22-11-22 17:50(최예닮)

fix: #12 cors 설정 수정 22-11-22 17:50(최예닮)

---

socket.js

fix: #12 cors origin 값 수정 22-11-22 17:52(최예닮)

fix: #12 cors origin 값 수정 22-11-22 17:52(최예닮)

---

socket.js

fix: #12 users, socketRoom 객체 추가 22-11-22 17:55(최예닮)

fix: #12 users, socketRoom 객체 추가 22-11-22 17:55(최예닮)

---

socket.js

fix: #12 cors 수정 및 join에 console.log 추가 22-11-22 18:01(최예닮)

fix: #12 cors 수정 및 join에 console.log 추가 22-11-22 18:01(최예닮)

---

socket.js

fix #12 webRTC 프론트와의 연결 테스트 코드 22-11-22 18:11 (김민섭)

fix #12 webRTC 프론트와의 연결 테스트 코드 22-11-22 18:11 (김민섭)

---

socket.js

fix: #12 console.log 위치 변경 22-11-22 18:24(최예닮)

fix: #12 console.log 위치 변경 22-11-22 18:24(최예닮)

---

socket.js

fix: #12 cors 수정 22-11-22 18:34(최예닮)

fix: #12 cors 수정 22-11-22 18:34(최예닮)

---

socket.js

fix: #12 offer 오류 수정중 22-11-22 18:46(최예닮)

fix: #12 offer 오류 수정중 22-11-22 18:46(최예닮)

---

socket.js

fix: #12 answer 오류 수정중 22-11-22 18:50(최예닮)

fix: #12 answer 오류 수정중 22-11-22 18:50(최예닮)

---

socket.js

fix: #12 socket.to 오류 수정중 22-11-22 18:53(최예닮)

fix: #12 socket.to 오류 수정중 22-11-22 18:53(최예닮)

---

jwt/jwt-utils.js
server.js
socket.js

1. fix: refreshToken expire 시간 2m -> 30m으로 변경 22-11-23 11:49 
2. fix: socket.js disconnect 부분 주석 해제 22-11-23 13:11

fix: socket.js disconnect 부분 주석 해제 22-11-23 13:11 (김민섭)

---

socket.js

fix: socket.js console.log 수정 22-11-23 14:02 (김민섭)

fix: socket.js console.log 수정 22-11-23 14:02 (김민섭)

---

socket.js

feat: socket.js 86, 87, 88 Line disconnect 작업을 위한 console.log 추가

feat: socket.js 86, 87, 88 Line disconnect 작업을 위한 console.log 추가 22-11-23 14:50 (김민섭)

---

socket.js

feat: 89 Line console.log 추가 22-11-23 15:13 (김민섭)

feat: 89 Line console.log 추가 22-11-23 15:13 (김민섭)

---

socket.js

feat: 98 Line console.log 추가 22-11-23 15:13 (김민섭)

feat: 98 Line console.log 추가 22-11-23 15:13 (김민섭)

---

socket.js

fix: socket.js 테스트 끝난 필요없는 console.log 삭제 22-11-23 15:47 (김민섭)

fix: socket.js 테스트 끝난 필요없는 console.log 삭제 22-11-23 15:47 (김민섭)

---

socket.js

feat: socket.js 91 Line 테스트 console.log 추가 22-11-23 15:52 (김민섭)

feat: socket.js 91 Line 테스트 console.log 추가 22-11-23 15:52 (김민섭)

---

socket.js

fix: socket.js disconnect 부분 socket.leave 적용 22-11-23 16:23 (김민섭)

fix: socket.js disconnect 부분 socket.leave 적용 22-11-23 16:23 (김민섭)

---

controller/mockInterview.controller.js
routes/mockInterview.routes.js
service/mockInterview.service.js

- 모의 면접 질문 랜덤 선별 API response 값 수정 
- status값 추가
- response 스타일 변경
```
{
"category": "node",
"questionArr": [
"Restful API란 무엇인가요?",
"ORM에 대해서 설명하세요.",
"이벤트기반 프로그래밍이란 무엇인가요?"
]
}

style: #13 모의 면접 질문 랜덤 선별 response 값 스타일 수정 22-11-24 13:11(백지영)

---

service/members.service.js

fix: #3 login 기능 bcrypt compare에 await 추가 22-11-24 13:17 (김민섭)

fix: #3 login 기능 bcrypt compare에 await 추가 22-11-24 13:17 (김민섭)

---

controller/members.controller.js
models/members.js
repository/members.repository.js
service/members.service.js

- 회원 가입 오류 수정 (추가 수정 예정)
- members 스키마 수정
- getMemberInfo(마이페이지) API response에 프로필 이미지 추가

feat: #4 getMemberInfo(마이페이지) API response에 프로필 이미지 추가 22-11-24 14:06

---

controller/mockInterview.controller.js

chore: #13 로그 확인중 22-11-24 14:37(백지영)

chore: #13 로그 확인중 22-11-24 14:37(백지영)

---

controller/mockInterview.controller.js

chore: #13 모의면접 질문 랜덤 선별  로그 확인중 22-11-24 14:39(백지영)

chore: #13 모의면접 질문 랜덤 선별  로그 확인중 22-11-24 14:39(백지영)

---

controller/mockInterview.controller.js
routes/mockInterview.routes.js

chore: #13 모의면접 질문 랜덤 선별 API 요청 GET -> POST로 변경 22-11-24 15:06(백지영)

chore: #13 모의면접 질문 랜덤 선별 API 요청 GET -> POST로 변경 22-11-24 15:06(백지영)

---

app.js
controller/mockInterview.controller.js
jwt/jwt-utils.js
models/members.js
models/mockInterviewResult.js
package-lock.json
package.json
repository/mockInterview.repository.js
routes/mockInterview.routes.js
service/mockInterview.service.js

- 모의면접 결과 저장 API 1차 구현 완료
- 모의 면접 결과 전체 조회 API 1차 구현 완료
- 모의 면접 결과 상세 조회 API 1차 구현 완료

feat: #14, #15 모의 면접 결과 저장, 결과 조회 API들 1차 구현 완료

---

controller/mockInterview.controller.js
repository/mockInterview.repository.js
service/mockInterview.service.js

- 모의 면접 결과 저장 API response에 저장된 결과의 sequence값 추가

feat: #14 모의 면접 결과 저장 API response 값 수정 22-11-25 00:49(백지영)

---

models/members.js

- memberSchema Date 대한민국 표준시로 들어가게끔 수정

fix: #2 memberSchema Date 대한민국 표준시로 들어가게끔 수정 22-11-25 02:21(백지영)

---

models/company.js
models/expirationMember.js
models/members.js
models/mockInterview.js
models/mockInterviewResult.js
models/refresh.js
models/reservation.js

- 모든 Schema Date 대한민국 표준시로 들어가게끔 수정

fix: 모든 Schema Date 대한민국 표준시로 들어가게끔 수정 22-11-25 10:35(백지영)

---

models/room.js
socket.js

구현 내용
app.get 으로 미들웨어 주고 db 저장 없이 socket 값에 locals 에서 받아온 정보들 보내줌

feat: #12 db저장 없이 토큰값 받아오고 join까지 되는지 테스트 22-11-28 14:58(최예닮)

---

socket.js

fix: #12 ice,offer,answer,disconnecting 으로 수정 22-11-28 16:20(최예닮)

fix: #12 ice,offer,answer,disconnecting 으로 수정 22-11-28 16:20(최예닮)

---

app.js
controller/userController.js
models/user.js
routes/users.routes.js

feat:#12 webRTC 연결을 위해  카카오 로그인 테스트22-11-28 16:34(최예닮)

feat:#12 webRTC 연결을 위해  카카오 로그인 테스트22-11-28 16:34(최예닮)

---

controller/userController.js

fix: #12 카카오 로그인 jwt 시크릿키 변경, locals.user -> locals.members 로 변경 22-11-28 16:40(최예닮)

fix: #12 카카오 로그인 jwt 시크릿키 변경, locals.user -> locals.members 로 변경 22-11-28 16:40(최예닮)"

---

controller/members.controller.js
routes/index.routes.js
routes/room.routes.js
socket.js

room 생성 API 1차 구현

---

routes/room.routes.js

fix: #12 routes get에서 memberEmail -> {memberEmail}로 변경 22-11-28 20:14(최예닮)

fix: #12 routes get에서 memberEmail -> {memberEmail}로 변경 22-11-28 20:14(최예닮)

---

routes/room.routes.js

fix: #12 routes room 코드수정 22-11-28 20:20(최예닮)

fix: #12 routes room 코드수정 22-11-28 20:20(최예닮)

---

routes/room.routes.js

fix: #12 room.routes 코드 수정 22-11-28 20:27(최예닮)

fix: #12 room.routes 코드 수정 22-11-28 20:27(최예닮)

---

routes/room.routes.js

fix: #12 routes room 코드수정 2차 22-11-28 20:31(최예닮)

fix: #12 routes room 코드수정 2차 22-11-28 20:31(최예닮)

---

app.js

fix: #12 app.js cors 코드 수정 22-11-28 21:04(최예닮)

fix: #12 app.js cors 코드 수정 22-11-28 21:04(최예닮)

---

jwt/jwt-utils.js

fix: #3 토큰 시간 12h 으로 변경 22-11-28 21:08(최예닮)

fix: #3 토큰 시간 12h 으로 변경 22-11-28 21:08(최예닮)

---

routes/room.routes.js

fix: #12 routes middleware 제거 22-11-28 21:34(최예닮)

fix: #12 routes middleware 제거 22-11-28 21:34(최예닮)

---

routes/room.routes.js

fix: #12 routes room middleware 추가 22-11-28 21:45(최예닮)

fix: #12 routes room middleware 추가 22-11-28 21:45(최예닮)

---

routes/room.routes.js

fix: #12 routes room 전체 주석처리 22-11-28 21:48(최예닮)

fix: #12 routes room 전체 주석처리 22-11-28 21:48(최예닮)

---

package-lock.json
routes/index.routes.js

fix: #12 routes 수정 22-11-28 21:52(최예닮)

fix: #12 routes 수정 22-11-28 21:52(최예닮)

---

app.js
controller/members.controller.js
repository/members.repository.js
service/members.service.js

chore: #4 회원 정보 수정 API에 로그 추가 22-11-28 23:54(백지영)

---

middleware/upload_middleware.js

chore: #4 upload_middleware에 로그 추가 22-11-20 00:13(백지영)

---

routes/members.routes.js

- 회원 정보 수정 API 요청 PUT -> PATCH 로 변경

style: #4 회원 정보 수정 API 요청 PUT -> PATCH 로 변경 22-11-29 00:30(백지영)

---

socket.js

fix: #12 socket candidate 위치 변경 22-11-29 01:08(최예닮)

fix: #12 socket candidate 위치 변경 22-11-29 01:08(최예닮)

---

socket.js

fix: #12 candidate 원위치로 22-11-29 01:51(최예닮)

fix: #12 candidate 원위치로 22-11-29 01:51(최예닮)

---

routes/members.routes.js

chore: #4 회원 정보 수정 요청 uri 변경 22-11-29 02:10(백지영)

---

controller/members.controller.js
jwt/jwt-utils.js
jwt/refreshToken.js
models/refresh.js
repository/members.repository.js
routes/members.routes.js
service/members.service.js

비밀번호 변경 API & refreshToken DB 저장 기능 구현 22-11-30 11:37 (김민섭)
1. 비밀번호 API
2. refreshToken DB에 저장 및 비교 기능

비밀번호 변경 API & refreshToken DB 저장 기능 구현 22-11-30 11:37 (김민섭)

---

controller/members.controller.js
jwt/jwt-utils.js
models/members.js
repository/members.repository.js
service/members.service.js

#4 members/delete api 기능 구현 22-11-30 14:59 (김민섭)
회원 삭제 API 1차 구현

#4 members/delete api 기능 구현 22-11-30 14:59 (김민섭)

---

controller/mockInterview.controller.js
routes/mockInterview.routes.js

- 모의면접 질문 tts 구현 테스트중 API 요청 GET->POST로 변경

test: #14 모의면접 질문 tts 구현 테스트중 API 요청 GET->POST로 변경 22-11-30 17:05(백지영)

---

controller/members.controller.js
jwt/jwt-utils.js
middleware/auth_middleware.js
models/members.js
repository/members.repository.js
routes/members.routes.js
service/members.service.js

feat: #4 마이페이지 회원 정보 수정 API 바디 값 추가 22-12-01 19:10 (김민섭)

feat: #4 마이페이지 회원 정보 수정 API 바디 값 추가 22-12-01 19:10 (김민섭)

---

jwt/jwt-utils.js
middleware/auth_middleware.js
models/mockInterviewResult.js
package-lock.json

fix: 몽고DB 타임존 문제 해결중 22-12-01 20:45(백지영)

fix: 몽고DB 타임존 문제 해결중 22-12-01 20:45(백지영)

---

.gitignore
models/mockInterviewResult.js

- 몽고DB 타임존 문제 해결중 -> date-fns 사용

fix: 몽고DB 타임존 문제 해결중 22-12-01 22:21(백지영)

---

repository/mockInterview.repository.js

fix: #14 모의 면접 결과 저장 시간 원래대로 되돌림 ㅠㅠ 22-12-02 01:52(백지영)

---

models/members.js

- members 스키마 생일 required true 주석처리

chore: #2 members 스키마 생일 required true 주석처리 22-12-02 20:36 (백지영)

---

controller/members.controller.js
schedule/schedule.js
service/members.service.js

fix: members 비밀번호 변경 API refresh Token 삭제 안되는 오류 해결 22-12-02 20:41 (김민섭)

fix: members 비밀번호 변경 API refresh Token 삭제 안되는 오류 해결 22-12-02 20:41 (김민섭)

---

app.js
jwt/refreshToken.js
package-lock.json
package.json
routes/index.routes.js

feat: express-rate-limit 추가 22-12-03 18:26 (김민섭)

feat: express-rate-limit 추가 22-12-03 18:26 (김민섭)

---

app.js
loadtest.json
routes/members.routes.js

feat: 부하테스트 구현 완료 22-12-03 21:28 (김민섭)

feat: 부하테스트 구현 완료 22-12-03 21:28 (김민섭)

---

service/mockInterview.service.js

refactor: #13 getRandomQuestions for문 제거 22-12-03 21:41 (김민섭)

refactor: #13 getRandomQuestions for문 제거 22-12-03 21:41 (김민섭)

---

.github/workflows/node.js.yml
index.pug

github actions 테스트 중 22-12-05 11:10

github actions 테스트 중 22-12-05 11:10

---

.github/workflows/node.js.yml

github actions 테스트 중 22-12-05 12:05

github actions 테스트 중 22-12-05 12:05

---

jwt/jwt-utils.js

fix: #3 AccessToken에 정보 추가 22-12-05 21:31 (김민섭)
1. memberName
2. img

fix: #3 AccessToken에 정보 추가 22-12-05 21:31 (김민섭)

---

jwt/jwt-utils.js

fix: #3 AccessToken에 정보 추가 22-12-05 22:12 (김민섭)
1. memberEmail 추가

fix: #3 AccessToken에 정보 추가 22-12-05 22:12 (김민섭)

---

controller/mockInterview.controller.js
models/mockInterview.js
repository/mockInterview.repository.js
routes/mockInterview.routes.js
service/mockInterview.service.js

feat: 회원 커스텀 질문 생성 API 1차 구현 완료 22-12-06 14:11(백지영)

---

controller/mockInterview.controller.js
repository/mockInterview.repository.js
routes/mockInterview.routes.js
service/mockInterview.service.js

feat: #15 모의 면접 결과 삭제하기 API 1차 구현 완료 22-12-06 14:52(백지영)

---

controller/members.controller.js
repository/members.repository.js
service/members.service.js

fix: #4 마이페이지 update API 수정 22-12-07 11:22 (김민섭)
1. profileImg 변경 시 즉시 반영
2. members 정보 변경 시 즉시 반영

fix: #4 마이페이지 update API 수정 22-12-07 11:22 (김민섭)

---

controller/members.controller.js
service/members.service.js

기능 구현 내용
1. .env 파일에 암호를 추가하여 프론트와 백엔드가 email 인증이 확인되었는지 알 수 있도록 기능구현

feat: #2 프론트 백엔드 email 인증 완료시 암호전달 validate 추가 22-12-08 10:53(최예닮)

---

package-lock.json
package.json
test/unit/members.test.js

feat: Test 코드 기본 폼 커밋 22-12-08 20:35 (김민섭)

feat: Test 코드 기본 폼 커밋 22-12-08 20:35 (김민섭)

---

app.js
package-lock.json
package.json
schedule/schedule.js
service/members.service.js
test/integration/members.int.test.js

feat: members 통합 테스트 작성 22-12-08 21:57 (김민섭)

feat: members 통합 테스트 작성 22-12-08 21:57 (김민섭)

---

.github/workflows/node.js.yml
schedule/schedule.js

fix: github/workflows/yml 파일 test 기능 추가 22-12-09 10:17 (김민섭)
fix: nodeSchedule 시간 변경 22-12-08 22:08

fix: github/workflows/yml 파일 test 기능 추가 22-12-09 10:17 (김민섭)

---

.github/workflows/node.js.yml

fix: github/workflows/yml 파일 npm upgrade 추가 22-12-09 10:23 (김민섭)

fix: github/workflows/yml 파일 npm upgrade 추가 22-12-09 10:23 (김민섭)

---

.github/workflows/node.js.yml
controller/members.controller.js

fix: 회원 탈퇴 오류 수정 중 22-12-09 22:42(백지영)

---

.github/workflows/node.js.yml
app.js
config/tracer.js
controller/mockInterview.controller.js
package-lock.json
package.json

feat: tracer config 추가 22-12-09 14:10 (김민섭)

feat: tracer 추가 22-12-09 14:10 (김민섭)

---

middleware/morgan_middleware.js
package-lock.json
package.json

구현 내용
1.  dev -> combined 변경
2. 주석 추가

fix: morgan dev 에서 combined 로 변경 및 주석 추가 22-12-09 14:14(최예닮)

---

.gitignore
app.js
controller/members.controller.js
middleware/morgan_middleware.js

구현 내용
1. morgan 미들웨어 tracer 이랑 연결하게 함

feat: tracer + morgan 구현 22-12-09 14:27(최예닮)

---

app.js
controller/members.controller.js
file.log

feat: members/login tracer 추가 22-12-09 14:31 (김민섭)

feat: members/login tracer 추가 22-12-09 14:31 (김민섭)

---

file.log
middleware/morgan_middleware.js

fix: morgan statusCode 400 -> statusCode 200 으로 변경 22-12-09 14:41(최예닮)

 fix: morgan statusCode 400 -> statusCode 200 으로 변경 22-12-09 14:41(최예닮)

---

app.js

fix: 주석추가 app.js 22-12-09 15:03(최예닮)

fix: 주석추가 app.js 22-12-09 15:03(최예닮)

---

app.js
controller/members.controller.js

구현 내용
1. throw new Error 를 Sentry issues 로 볼 수 있게 구현완료

feat: Sentry throw new Error 로 받을 수 있게 구현완료 22-12-09 20:56(최예닮)

---

app.js
controller/members.controller.js
package-lock.json
package.json

style: Sentry 슬랙 메세지 추가 22-12-10 19:47(최예닮)

style: Sentry 슬랙 메세지 추가 22-12-10 19:47(최예닮)

---

controller/members.controller.js
controller/mockInterview.controller.js

style: controller 에 Sentry 코드 추가 22-12-10 19:58(최예닮)

style: controller 에 Sentry 코드 추가 22-12-10 19:58(최예닮)

---

app.js
server.js

server.js 삭제 22-12-10 21:38 (김민섭)

server.js 삭제 22-12-10 21:38 (김민섭)

---

app.js
config/tracer.js
controller/mockInterview.controller.js
controller/social.controller.js
jwt/jwt-utils.js
passport/kakao.js
passport/kakaoStrategy.js
routes/videos.routes.js
service/reservation.service.js

refector: console.log 및 tracer 삭제 22-12-10 22:13 (김민섭)

refector: console.log 및 tracer 삭제 22-12-10 22:13 (김민섭)

---

controller/members.controller.js
service/members.service.js

style: 로그인시 가입되지 않은 이메일 401 에러 띄워줌 22-12-14 11:39(백지영)

---

controller/members.controller.js
service/members.service.js

fix: 비밀번호 찾기 API에 통신 확인용 키 추가 22-12-14 12:51(백지영)

---

routes/members.routes.js
test/integration/int.test.js

fix: 비밀번호 찾기 API URL 변경 22-12-14 15:57(백지영)

---

controller/reservation.controller.js
service/reservation.service.js

fix: 면접예약 주석 품 22-12-27 19:53(최예닮)

fix: 면접예약 주석 품 22-12-27 19:53(최예닮)
